### ISSUE TITLE
Question: Prevent click on submit-button inside form from submitting

### ISSUE THREAD

**Issue by FloWi** [collegevine/purescript-elmish#43]
Hi!

I want to be able to press "Enter" in all the fields of my form and have it preform the default action. I did some research and found that people use a submit button and prevent the button from actually submitting. There are three different ways to achieve that in javascript.

```html
<form onsubmit="return false;">
<form onsubmit="event.preventDefault();">
<button onclick="event.preventDefault();">
```
I wanted to go with the first approach and just return false in the forms' onSubmit, but that doesn't compile, since it expects `Effect Unit`. 

I also haven't found a way to call a method on the event. Is that even possible in purescript, since it's not OO?
It'd be great if someone could give me some advice for both approaches.

Thanks in advance!
Regards,
Florian

**Comment by fsoikin** [comment]
Hi @FloWi! 
Thank you very much for trying out Elmish despite almost no documentation. I appreciate the attention very much and can help with questions along your journey (within reasonable bounds).

From your description, I'm assuming you're using `purescript-elmish-html` for rendering your DOM (because Elmish itself doesn't prescribe a particular way to render). 

The first thing to understand is that the event handlers in `purescript-elmish-html` are very much a work in progress. There is a three-way tension there between (1) ergonomics, (2) type safety, and (3) runtime overhead. In the underlying JS all event handlers are basically of type `SyntheticEvent -> Effect Unit`, meaning they take an event object as a parameter and perform some effect. And this is how most events are modeled in `elmish-html` - they are all `Foreign -> Effect Unit`, where `Foreign` stands for the synthetic event object.

With `onClick`, however, we have discovered that in the vast majority of cases it doesn't actually use the event object, and all we want to do is just dispatch a message. So it became very tedious and awkward to write `onClick: dispatch <| \_ -> Msg` instead of `onClick: dispatch Msg`. So we decided to remove the `Foreign` parameter altogether. This made ergonomics slightly better at the expense of functionality. 

Like I said above: it's a work in progress. We might come up with a better way to do event handlers in the future, but for now, this is what we have.

That said, you do have quite a few options to achieve your objective.

## Option 1: redefine the type of `onClick`
Though `onClick` is defined as `Effect Unit` in the library, you can just go ahead and define your own. To do this, you'll need to base your props row on the existing one for `button` and define your own element constructor:

```PureScript
import Elmish.HTML (OptProps_button)
import Elmish.HTML.Internal (StyledTag_, styledTag_)
import Web.Event.Internal.Types (Event)

type OptProps_myButton r =
  ( onClick :: EffectFn1 Event Unit
  | OptProps_button r
  )

-- Replace `styledTag_` with `createElement . unsafeCreateDOMComponent` if you're not using styled tags
myButton_ = styledTag_ "myButton" :: StyledTag_ OptProps_myButton
```

Then you can use this constructor with the new `onClick` type and call `preventDefault` on it:

```PureScript
view = 
  form
  [ ...
  , myButton_ "btn btn-primary" 
      { type: "submit"
      , onClick: mkEffectFn1 \e -> preventDefault e *> dispatch ButtonClicked 
      } 
      "Click me!"
  ]
```

This option is preferable if you'll be using this handler a lot in different places. 

## Option 2: `unsafeCoerce`
Basically the same, but without defining your own constructor and props row. Just `unsafeCoerce` the event handler and be done with it:

```PureScript
view = 
  form
  [ ...
  , btton_ "btn btn-primary" 
      { type: "submit"
      , onClick: unsafeCoerce $ mkEffectFn1 \e -> preventDefault e *> dispatch ButtonClicked 
      } 
      "Click me!"
  ]
```

This option is less safe, but less ceremony. Pick your poison :-)

## Option 3: use `onKeyDown` instead
Instead of using a `type=submit` button in the first place, consider using `onKeyDown` handler on the form itself. You can get the event's `key` attribute via `readForeign` and see if it's the `Enter` key:

```PureScript
view = 
  form_
    { onKeyPress: \e ->
        case readForeign e :: Maybe { key :: _ } of
          Just { key: "Enter" } -> dispatch FormSubmitted
          _ -> pure unit
    }
    [ ...
    , button_ "btn btn-primary" { onClick: dispatch FormSubmitted } "Click me!"
    ]
```

Personally, I would much prefer this option, because it has fewer ad-hoc effects (i.e. `preventDefault`), and thus is a bit easier to comprehend later.

**Comment by FloWi** [comment]
Hi @fsoikin!

Wow, thanks a lot for the time to write such a nice response! I didn't expect that and highly appreciate it! 

I usually work on the backend and both purescript and frontends are quite new to me. A friend of mine and former colleague suggested elmish and I really like it, since I also had fun with elm in the past. 

elmish brings together two worlds I enjoy working in - (most of) the elm-architecture that provides a clear structure to the project and purescript as a way more powerful language than elm. 

I wasn't sure why onClick only works with `Effect Unit` and it was very educational to learn your thought process behind the design decisions.
