### ISSUE TITLE
Preact Runtime?

### ISSUE THREAD

**Issue by jgarte** [collegevine/purescript-elmish#62]
Hi, how hard would it be to get purescript-elmish to work with a [preact](https://preactjs.com/) runtime?

**Comment by fsoikin** [comment]
Hi @jgarte!

Elmish uses only a few base APIs from React (such as `createElement` and `setState`), so I would imagine it should just work with preact. All you need to do is install a redirect so that `import 'react'` and `import 'react-dom'` resolve to preact instead of React.

I have not tried this myself though, and I'm not aware of anybody else who did. So if you decide to try it, please keep us updated. I'm very excited to see what you can do.

Cheers!
