### ISSUE TITLE
Straightforward way to make unit tests for effectful `update` in isolation

### ISSUE THREAD

**Issue by CodingArdor** [collegevine/purescript-elmish#89]
Suppose we have these messages:

```haskell
data Message
  = Step1
  | Step2 Date
```

Also suppose we have this `update` function for which dispatching `Step1` causes it to fire an effect _(`nowDateTime` of `Effect.Now`)_ and dispatch `Step2` with the result, ultimately updating the `dateNow` field of the state with it:

```haskell
update :: State -> Message -> Transition Message State
update state Step1 = do
  fork do
    d <- liftEffect nowDateTime
    pure $ Step2 $ date d
  pure state
update state (Step2 d) = do
  pure state { dateNow = d }
```

I want to make a unit test **without any dependency on the UI** _(i.e., without using `purescript-elmish-testing-library`)_ that asserts the correctness of `update` when handling the `Step1` message. I can think of two ways to do this:
1. Check whether the resulting state is as expected
2. Check whether `Step2` will be dispatched _(i.e., is `Step2` in the returned `Transition`?)_

While unit testing an _effect-free_ `update` is straightforward via approach 1, both ways do **not** seem to be viable for testing an _effectful_ `update` due to the following:
1. Manually calling `update` with `Step1` does not result in `Step2` being dispatched, so the state in the returned `Transition` is not yet the expected state
2. There does not seem to be a way to determine whether a particular message is to be dispatched by _(i.e., is in the array of messages in)_ the returned `Transition`

I would like to ask whether there exists a straightforward way _(which I may have overlooked)_ to accomplish this.

**Comment by fsoikin** [comment]
## Short answer
No, there is no straightforward way. UI is complicated, that's why we have libraries to do it.

## Long answer
First, I'd like to address a possible misconception: the `Transition` value does not contain "an array of messages" that one could possibly inspect. Instead, it contains an array of _effects_, which would produce messages when executed. Look at your own snippet: the parameter to the `fork` function is an effect, not a message. This may make more sense if you consider that effects can be long-running, such as calling a server API.

So, in order to see the full progression of updates, you essentially have to run the event loop. It's the core component of any UI library or framework: a loop that constantly picks up new messages, calls update, picks up any new messages from that, rinse and repeat. 

In `elmish-testing-library` we basically offload this work to React. It's the React library that is running the event loop. More precisely, it's the React library in conjunction with the browser. But that's details.

But if you don't want React, you have to run your own event loop. Which can be tricky. For your toy example above, you might do something like:

```haskell
loop :: forall state message. 
  state 
  -> message 
  -> (state -> message -> Transition message state) 
  -> Aff { finalState :: state, issuedMessages :: Array message }
loop initialState firstMessage update = do
  finalState /\ issuedMessages <- runWriterT $ go initialState firstMessage
  pure { finalState, issuedMessages }
  where
    go :: state -> messages -> WriterT (Array message) Aff state
    go s m = do
      let Transision s' effects = update s m
      moreMessages <- runEffect `traverse` effects
      tell moreMessages -- Record these new messages to WriterT
      foldM go s' moreMessages -- Recursively process every message, threading the state through

    -- Run the command, wait for its first `dispatch` call and return its parameter
    runEffect :: Command Aff message -> Aff message
    runEffect cmd = 
      makeAff \callback ->
        launchAff_ $
          cmd { dispatch: callback <<< Right, onStop: \_ -> pure unit }
```

You can see how complicated it is already, and it's not even doing all that it should. If you look closely at `runEffect`, you'll see that it assumes that the command will generate exactly one message, while in reality a command can generate zero or more. And then it does a depth-first search (if you think of forking messages as a tree) rather than breadth-first, as it would normally be run in a browser.

This is why we have UI libraries. And this is why Elmish is built on top of React rather than trying to do this (and many other things) on its own.
